### PR TITLE
feat: add configurable CORS support

### PR DESCRIPTION
**Pull request by bharatnpti**
feat(cors): add configurable CORS support with allowed origins

- Implement CORS functionality with configurable allowed origins, disabled by default
- If enabled, defaults to '*' if allowedOrigins is null, empty, or contains only null values
- Adds flexibility for specifying allowed origins, methods, headers and url patterns through configuration properties

### CODE REVIEW

**Comment by bharatnpti** [comment]
TODO - Update Documentation - Done

**Comment by bharatnpti** [comment]
implements - https://github.com/lmos-ai/lmos-runtime/issues/36

**Comment by kaikreuzer** [comment]
@bharatnpti Are you still working on this? This blocks upgrading lmos-demo to any newer version of lmos-runtime...

**Comment by bharatnpti** [comment]
reopen

**Comment by bharatnpti** [comment]
reopen

**Comment by bharatnpti** [comment]
reopen

**Comment by bharatnpti** [comment]
reopen

**Pull request closed without merging**
